### ISSUE TITLE
The publisher should not be IETF

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-misc#15]
- Originally posted by @ronaldtse in https://github.com/ietf-tools/relaton-data-misc/issues/5#issuecomment-1042930490
- Subsequently came up again in https://github.com/ietf-ribose/bibxml-service/issues/234

**Comment by ronaldtse** [comment]
Ah right, this is a relaton-ietf issue. Linking it there.

**Comment by ronaldtse** [comment]
I was wrong. The current repo is correct:

Look at this data:
https://github.com/ietf-tools/relaton-data-misc/blob/fcc1aae9869668935f7823724e2f74f89c07332b/data/reference.PKCS.1.1991.yaml#L22-L27

There is no publisher IETF.

I suspect it is the BibXML service that is adding the IETF organization. Can @strogonoff please confirm?

**Comment by strogonoff** [comment]
Can I have an example where BibXML service adds the organization? 

Here it’s not IETF: https://dev.bibxml.org/public/rfc/bibxml2/reference.PKCS.9.1993.xml

Perhaps, if you are testing locally, your sources were not indexed since that time?

**Comment by ronaldtse** [comment]
This screenshot was taken from the file you provided in https://github.com/ietf-ribose/bibxml-service/issues/222 😉

**Comment by ronaldtse** [comment]
Apparently this is not the case anymore, so we can close this?

**Comment by strogonoff** [comment]
> This screenshot was taken from the file you provided in [ietf-ribose/bibxml-service#222](https://github.com/ietf-ribose/bibxml-service/issues/222) 😉

Ah, that’s been a while back :)
